name: CD-Liara
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: update-liara
        env:
          LIARA_HEYLEE_NET_TOKEN: ${{ secrets.LIARA_HEYLEE_NET_TOKEN }}
        run: |
          npm i -g @liara/cli@6
          liara deploy --platform=angular --app="heylee-app" --api-token="$LIARA_HEYLEE_NET_TOKEN" --no-app-logs --port=80
